spring.application.name=payflow-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/payflow_db
spring.datasource.username=payflow_user
spring.datasource.password=payflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=localhost
spring.data.redis.port=6379